package:
  name: q2cli
  version: "2017.2.0"

source:
  git_url: https://github.com/qiime2/q2cli.git
  git_rev: 2017.2.0
build:
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - q2cli = q2cli:main
    #
    # Would create an entry point called q2cli that calls q2cli.main()

    - qiime=q2cli.__main__:qiime

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - click
    - qiime2 2017.2.*
    - pip

  run:
    - python
    - setuptools
    - click
    - qiime2 2017.2.*
    - pip

test:
  # Python imports
  imports:
    - q2cli

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - qiime --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  #summary: Summary of the package
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
