package:
  name: q2-quality-filter
  version: "2017.2.0"

source:
  git_url: https://github.com/wasade/q2-quality-filter.git
  git_rev: 2017.2.0
build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - q2-quality-filter = q2-quality-filter:main
    #
    # Would create an entry point called q2-quality-filter that calls q2-quality-filter.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - qiime2 2017.2.*
    - q2templates 2017.2.*
    - pandas
    - q2-types 2017.2.*

  run:
    - python
    - setuptools
    - qiime2 2017.2.*
    - q2templates 2017.2.*
    - pandas
    - q2-types 2017.2.*

test:
  # Python imports
  imports:
    - q2_quality_filter
    - q2_quality_filter.test

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/wasade/q2-quality-filter
  license: BSD-3-Clause
  summary: 'Basic FASTQ quality filtering'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
