package:
  name: q2-composition
  version: "2017.2.0"

source:
  git_url: https://github.com/qiime2/q2-composition.git
  git_rev: 2017.2.0
build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - q2-composition = q2-composition:main
    #
    # Would create an entry point called q2-composition that calls q2-composition.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - qiime2 2017.2.*
    - q2-types 2017.2.*
    - bokeh
    - biom-format >=2.1.5,<2.2.0
    - scipy
    - scikit-bio

  run:
    - python
    - setuptools
    - qiime2 2017.2.*
    - q2-types 2017.2.*
    - bokeh
    - biom-format >=2.1.5,<2.2.0
    - scipy
    - scikit-bio

test:
  # Python imports
  imports:
    - q2_composition
    - q2_composition.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  summary: 'Compositional statistics plugin for QIIME2.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
