package:
  name: q2templates
  version: "2017.2.0"

source:
  git_url: https://github.com/qiime2/q2templates.git
  git_rev: 2017.2.0
# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - q2templates = q2templates:main
    #
    # Would create an entry point called q2templates that calls q2templates.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - jinja2

  run:
    - python
    - jinja2

test:
  # Python imports
  imports:
    - q2templates
    - q2templates.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  #summary: Summary of the package
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
